# config.prod.yaml - 生产环境
app:
  name: "go-gin-gorm-wire-viper-zap"
  version: "0.1.0"
  env: "prod"

server:
  port: 8080
  mode: release
  max_multipart_mem: 8388608  # 8MB
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1048576   # 1MB

database:
  dsn: ""
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

log:
  level: "debug"
  filename: "logs/app.log"
  max_size: 100
  max_backups: 30
  max_age: 30
  compress: true

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600s

cron:
  specs:
    signal_test: "0 */5 * * * *"  # 每5分钟执行一次 (秒 分 时 日 月 星期)